baseURL = "https://digipete.github.io/quietspaceclub/"
languageCode = "en-us"
title = "Quiet Space Club"
theme = "hugo-saasify-theme"
enableRobotsTXT = true

[params]
  description = "Certification and community for neuroinclusive workspaces."
  images = ["images/og-image.jpg"]

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Certification"
    url = "/certification/"
    weight = 2

  [[menu.main]]
    name = "Community"
    url = "/community/"
    weight = 3

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5
